apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fcg-paymentsapi
  namespace: fcg-prod
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  
  tls:
  - hosts:
    - fcg-ingress.brazilsouth.cloudapp.azure.com
    secretName: payments-tls

  rules:
    - http:
        paths:
          - path: /payments(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: paymentsapi
                port:
                  number: 80
